### ISSUE TITLE
Beim Feedback wird der betroffene Artikel nicht referenziert

### ISSUE THREAD

**Issue by michaelmejaeger** [dbsystel/tech-stories#8]
Wenn ich Feedback zu einem Artikel einstelle, so wird nicht automatisch die URL des Artikels ergänzt, zu dem ich Feedback geben möchte. Dies bitte noch ergänzen, ansonsten kommt es sicher in Zukunft öfter zu Rückfragen.

**Comment by rdmueller** [comment]
ah, I see. We use the gitlab paramters but should use the github ones. Fix is on its way

?title=&body=
